:showtitle:
:doctitle:  Kong API Gateway on Kubernetes with Pulumi
:description:  Kong on Kubernetes with Pulumi
:homepage:  https://konghq.com

= Kong API Gateway on Kubernetes with Pulumi
Kat Morgan <usrbinkat@konghq.com>
v2.8, 2020-03-13
:toc:

== The Kong Laboratory - Kong API Gateway
=== About
The quest for resilience and agility has driven us into the modern age of micro-services. Bringing services to market on a micro service architecture demands utilization of sprawling technology offerings and tooling. Universally this journey includes an infrastructure orchestration phase, an application deployment phase, and a service publishing phase.

In this hands on series we will dive into using both Kong API Gateway for service publishing, and Pulumi to orchestrate our infrastructure, deploy our applications, and configure our Kong API Gateway.

=== Key Concepts

*Kong Gateway* is an API gateway and Ingress Controller. An API gateway is a reverse proxy that allows an organization to offer APIs as a product to internal and external clients via a centralized ingress point. An API gateway shows it’s true value when leveraged to consolidate capabilities such as authentication, session handling, rate limiting, traffic monitoring, and logging. These advanced routing features offload enforcement, maintenance, and visibility from the application teams improving their agility and consolidates this functional ownership into a central location improving global consistency and visibility.

*Pulumi* is a cloud engineering platform that brings infrastructure teams, developers, and security teams together through a unified software engineering process that accelerates innovation. The Pulumi platform and SDKs allow teams to build, deploy, and manage modern cloud applications faster and with more confidence, using any language, any architecture and any cloud. Supporting Modern Infrastructure as Code using popular programming languages including Python, JavaScript, TypeScript, Go and .NET/C#.

***

=== Host Setup

This article is designed for you to follow along with your MacOS or Linux laptop using https://kind.sigs.k8s.io/[Kubernetes-in-Docker] (https://kind.sigs.k8s.io/[kind]). Before starting, please check that you have installed all link:#prerequisite_dependencies[dependencies]. +

Okay, now that you have your dependencies, let's grab the code and get your system ready to build the lab platform. +

====

[start=1]
. Write Hosts File Entries to resolve your lab domain names locally
```sh
# Set ADDRESS to your public IP address if you plan to use keycloak
# https://kind.sigs.k8s.io/docs/user/configuration/#api-server

export ADDRESS=127.0.0.1
cat <<EOF | sudo tee -a /etc/hosts
${ADDRESS}  apps.kind.home.arpa
${ADDRESS}  portal.kong.kind.home.arpa
${ADDRESS}  manager.kong.kind.home.arpa
${ADDRESS}  keycloak.apps.kind.home.arpa
EOF
```

[start=2]
. Create docker volumes for persistent local container image caching +
```sh
docker volume create worker1
docker volume create controlplane1
```

[start=3]
. Clone the TheKongLaboratory git repo
```sh
git clone https://github.com/kong/TheKongLaboratory.git ~/thekonglaboratory
cd ~/thekonglaboratory
```

====


=== Pulumi Infrastructure as Code

Great! Reviewing our check list, we now have: +

* [*] Configured `/etc/hosts` to resolve our domain names to our local IP.
* [*] Created local cache volumes for kind node images.
* [*] Cloned the demo repo codebase.

Your system is ready to run the lab and we have the code! Next, before we can deploy the Kong API Gateway we need to initialize the Pulumi codebase and configure a https://www.pulumi.com/docs/intro/concepts/stack/#stacks[Stack]. +

====

[start=4]
. Configure Pulumi local state provider login
```sh
# Set a Pulumi local state login password
export PULUMI_CONFIG_PASSPHRASE=mypassword

# Run pulumi login --help for more state backend and login information
pulumi login --local
```

[start=5]
. Initialize & Select Pulumi Stack
```sh
# Download npm packages for Pulumi typescript IaC
npm install

# Initialize and select your pulumi stack
pulumi stack init thekonglaboratory
pulumi stack select thekonglaboratory
```

[start=6]
. Set Stack Configuration Variables +
```sh
# Create a Kong Enterprise License, an empty license will enable free mode
pulumi config set --secret kong:license "'{}'"

# Set enterprise to true if deploying with an enterprise license
pulumi config set kong:enterprise false
```
====

=== Deploy Kong API Gateway

Now, with your prep work done, it is time to start your Kind cluster and deploy Kong to it!

====
[start=7]
. Deploy Kong Gateway Stack
```sh
# Start Kind Kubernetes Cluster
clear; kind create cluster --config hack/kind/config.yml

# Pulumi Deploy Kong Gateway & Dependencies
pulumi up -y
```

[start=8]
. Go ahead and open up the Kong Manger UI !! +
>> https://manager.kong.kind.home.arpa/
====

=== Deploy a Sample App

Let's go ahead and test our new Kong API Gateway by deploying a sample application. +

====
[start=9]
. Deploy Sample App
```sh
cmd goes here
```

====

=== Conclusion
Now you have deployed a working Kong Gateway with Pulumi. From here you can continue with configuring kong manager and kong plugins, or you can start using the Kong Ingress Controller to publish services on your kind cluster via Kong.


== Appendix
=== Dependencies [[prerequisite_dependencies]]

[cols="1,1"]
|===
| *Dependency* | *Installation Docs*

| https://kubernetes.io/docs/reference/kubectl/kubectl[kubectl]
| https://kubernetes.io/docs/tasks/tools/install-kubectl-linux[Linux] / https://kubernetes.io/docs/tasks/tools/install-kubectl-macos[Mac]

| https://www.docker.com/[Docker]
| https://docs.docker.com/engine/install/#server[Linux] / https://docs.docker.com/desktop/mac/install/[Mac]

| https://kind.sigs.k8s.io[Kind]
| https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries[Linux] / https://kind.sigs.k8s.io/docs/user/quick-start/#installing-with-a-package-manager[Mac]

| https://helm.sh/docs/intro/install[Helm]
| https://helm.sh/docs/intro/install/#from-script[Linux] / https://helm.sh/docs/intro/install/#from-homebrew-macos[Mac]

| https://www.pulumi.com/docs/get-started/install/#installing-pulumi[Pulumi]
| https://www.pulumi.com/docs/get-started/install/#installing-pulumi[Linux] / https://www.pulumi.com/docs/get-started/install/#installing-pulumi[Mac]

| https://nodejs.org/[npm]
| https://github.com/nodesource/distributions#installation-instructions[Linux] / https://nodejs.org/en/download/[Mac]

| https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git client]
| https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Linux] / https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Mac]

| https://everything.curl.dev/get[curl client]
| https://everything.curl.dev/get/linux[Linux] / https://everything.curl.dev/get/macos[Mac]
|===

***

=== Cleanup
When you are finished with your local deployment you can clean up all lab artifacts in this order:app-name: +

. Destroy Kong Pulumi Stack
. Delete Kind Cluster
. Remove Docker Volumes
. Remove TheKongLaboratory Git Repo

====


[start=0]
. Unlock your local secret store.
```sh
cd ~/thekonglaboratory
export PULUMI_CONFIG_PASSPHRASE=mypassword
```

[start=1]
. Destroy Kong Pulumi Stack
```sh
pulumi --stack thekonglaboratory destroy -y
```

[start=2]
. Delete Kind Cluster
```sh
kind delete cluster --name=kong
```

[start=3]
. Remove Docker Volumes
```sh
docker volume rm worker1 controlplane1
```

[start=4]
. Remove TheKongLaboratory Git Repo
```sh
pulumi --stack thekonglaboratory stack rm -y
cd ~ && rm -rf ~/thekonglaboratory
```

====
